In [22]:
import numpy as np

In [23]:
# Задание 1
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
b = np.array(a)

In [25]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [27]:
print("Средние значения признаков: {}".format(a.mean(axis=0)))

Средние значения признаков: [2.  8.4]


In [28]:
mean_a = (a.mean(axis=0))
mean_a

array([2. , 8.4])

In [29]:
# Задание 2
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [30]:
# Задание 3
arr1, arr2 = a_centered[:, 0], a_centered[:, 1]
arr1
arr2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [31]:
a_centered_sp = (arr1@arr2) / (len (a_centered) - 1)
a_centered_sp

2.0

In [34]:
# Задание 4
m = np.cov(a.T)[0,1]
m

2.0

In [36]:
import pandas as pd

In [38]:
# Pandas. Задание 1
autors = pd.DataFrame({"author_id" : [1, 2, 3], "author_name" : ['Тургенев', 'Чехов', 'Островский']})
autors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [39]:
book = pd.DataFrame({"author_id" : [1, 1, 1, 2, 2, 3, 3], 
                     "book_title" : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     "price" : [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [41]:
# Pandas. Задание 2
authors_price = pd.merge (autors, book, on='author_id', how="outer")
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [46]:
# Pandas. Задание 3
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [49]:
# Pandas. Задание 4
authors_stat = authors_price.groupby('author_name').agg({'price' : ['min', 'max', 'mean']})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000